config/routes.rb
Rails.application.routes.draw do
  get '/products/competition', to: redirect('/competition'), as: 'competition_product'
  get '/competition' => 'product/competition#index'
  
  namespace :competition do
    resources :games
    resources :exercise_types
    resources :tournaments
    
    resources :seasons, only: [] do
      resources :participations, controller: 'season_participations', only: [:index, :new, :create] 
      resources :rankings, only: [:index]
      
      resources :matches, only: [:index] do
        collection do
          put :updates
        end
      end
      
      member do
        get :bracket
      end
    end
    
    resources :season_participations, only: [] do
      member do
        put :accept
        put :deny
      end
    end
    
    resources :competitors
    resources :matches, only: [:show]
  end
end

app/models/product/competition.rb
class Product::Competition < ::Product
end

app/models/season_participation.rb
class SeasonParticipation < ActiveRecord::Base
  include Applicat::Mvc::Model::Resource::Base
  
  STATES = [:accepted, :requested, :denied]
  EVENTS = [:accept, :deny]
  
  belongs_to :season, class_name: 'TournamentSeason'
  belongs_to :competitor
  
  scope :accepted, -> { where(state: 'accepted') }
  
  def self.order_by_state
    if Rails.env.production?
      order_by = ["case"]
      
      STATES.each_with_index.map do |status, index|
        order_by << "WHEN state='#{status}' THEN #{index}"
      end
      
      order_by << "end"
      order(order_by.join(" "))
    else
      order("FIELD(state, '#{STATES.join("','")}')")
    end
  end
  
  validates :season_id, presence: true
  validates :competitor_id, presence: true, uniqueness: { scope: :season_id }
  
  attr_accessible :season_id
  
  after_initialize :set_initial_state
      
  state_machine :state, initial: :requested do
    state :requested do
      validate :competitors_limit_of_tournament_not_reached  
    end
    
    state :accepted do
      validate :competitors_limit_of_tournament_not_reached  
    end
    
    event :accept do
      transition [:requested, :denied] => :accepted
    end
    
    event :deny do
      transition [:requested, :accepted] => :denied
    end
  end
  
  private 
  
  def set_initial_state
    self.state ||= :requested
  end
  
  def competitors_limit_of_tournament_not_reached 
    unless season.tournament.more_competitors_needed?(season)
      errors[:base] << I18n.t('activerecord.errors.models.season_participation.attributes.state.tournament_competitors_limit_reached')
    end
  end
end

app/controllers/competition/application_controller.rb
class Competition::ApplicationController < ::ApplicationController
  protected

  def voluntary_application_stylesheets
    ['voluntary/application', 'application'] 
  end

  def voluntary_application_javascripts
    ['voluntary/application', 'voluntary_competition/application', 'application'] 
  end
end

app/controllers/competition/competitors_controller.rb
class Competition::CompetitorsController < ::Competition::ApplicationController
  include ::Competition::BaseController
  include Applicat::Mvc::Controller::Resource
  
  load_and_authorize_resource
  
  rescue_from ActiveRecord::RecordNotFound, with: :not_found
  
  respond_to :html
  
  def index
  end
  
  def show
  end
  
  def new
    @competitor = current_user.competitors.new(params[:competitor])
  end
  
  def create
    @competitor = current_user.competitors.new(params[:competitor])
    
    if @competitor.save
      redirect_to [:competition, @competitor], notice: t('general.form.successfully_created')
    else
      render :new
    end
  end
  
  def edit
  end
  
  def update
    if @competitor.update_attributes(params[:competitor])
      redirect_to [:competition, @competitor], notice: t('general.form.successfully_updated')
    else
      render :edit
    end
  end

  def destroy
    @competitor.destroy
    redirect_to competition_competitors_path, notice: t('general.form.destroyed')
  end
  
  def resource
    @competitor
  end
  
  private
  
  def not_found
    redirect_to competition_competitors_path, notice: t('general.exceptions.not_found')
  end
end

app/controllers/competition/exercise_types_controller.rb
class Competition::ExerciseTypesController < ::Competition::ApplicationController
  include ::Competition::BaseController
  include Applicat::Mvc::Controller::Resource
  
  load_and_authorize_resource
  
  rescue_from ActiveRecord::RecordNotFound, with: :not_found
  
  respond_to :html
  
  def index
  end
  
  def show
    @exercise_type = ExerciseType.find(params[:id])
  end
  
  def new
    @exercise_type = ExerciseType.new(params[:exercise_type])
  end
  
  def create
    @exercise_type = ExerciseType.new(params[:exercise_type])
    
    if @exercise_type.save
      redirect_to [:competition, @exercise_type], notice: t('general.form.successfully_created')
    else
      render :new
    end
  end
  
  def edit
  end
  
  def update
    if @exercise_type.update_attributes(params[:exercise_type])
      redirect_to [:competition, @exercise_type], notice: t('general.form.successfully_updated')
    else
      render :edit
    end
  end

  def destroy
    @exercise_type.destroy
    redirect_to competition_exercise_types_path, notice: t('general.form.destroyed')
  end
  
  def resource
    @exercise_type
  end
  
  private
  
  def not_found
    redirect_to competition_exercise_types_path, notice: t('general.exceptions.not_found')
  end
end

app/controllers/competition/games_controller.rb
class Competition::GamesController < ::Competition::ApplicationController
  include ::Competition::BaseController
  include Applicat::Mvc::Controller::Resource
  
  load_and_authorize_resource
  
  rescue_from ActiveRecord::RecordNotFound, with: :not_found
  
  respond_to :html
  
  def index
  end
  
  def show
    @game = Game.find(params[:id])
  end
  
  def new
    @game = Game.new(params[:game])
  end
  
  def create
    @game = Game.new(params[:game])
    
    if @game.save
      redirect_to [:competition, @game], notice: t('general.form.successfully_created')
    else
      render :new
    end
  end
  
  def edit
  end
  
  def update
    if @game.update_attributes(params[:game])
      redirect_to [:competition, @game], notice: t('general.form.successfully_updated')
    else
      render :edit
    end
  end

  def destroy
    @game.destroy
    redirect_to competition_games_path, notice: t('general.form.destroyed')
  end
  
  def resource
    @game
  end
  
  private
  
  def not_found
    redirect_to competition_games_path, notice: t('general.exceptions.not_found')
  end
end

app/controllers/competition/matches_controller.rb
class Competition::MatchesController < ::Competition::ApplicationController
  include ::Competition::BaseController
  include Applicat::Mvc::Controller::Resource
  include ::Competition::Bracket
  
  load_and_authorize_resource class: 'TournamentMatch'
  
  def index
    @season = TournamentSeason.find(params[:season_id])
    @can_update_season = can?(:update, @season)
    @matches = @season.matches.where('matchday = ?', params[:matchday])
    render partial: 'competition/matches/collection', layout: false if request.xhr?
  end
  
  def updates
    @season = TournamentSeason.find(params[:season_id])
    @can_update_season = can?(:update, @season)
    
    if params[:matches].present?
      @input_matches = @season.consider_matches(params[:matches], params[:matchday])
    else
      @input_matches = []
    end
    
    unless params[:from_bracket].blank? || @input_matches.empty? || @input_matches.select{ |m| !m.errors.empty? }.any?
      @season.reload
      get_bracket_variables
    end
     
    render layout: false if request.xhr?
  end
end

app/controllers/competition/rankings_controller.rb
class Competition::RankingsController < ::Competition::ApplicationController
  include ::Competition::BaseController
  include Applicat::Mvc::Controller::Resource
  
  load_and_authorize_resource class: 'TournamentSeasonRanking'
  
  def index
    @season = TournamentSeason.find(params[:season_id])
    
    if @season.tournament.with_group_stage?
      rankings = @season.rankings.order('position ASC')
      groups_matchday = params[:matchday].to_i > @season.tournament.last_matchday_of_group_stage ? @season.tournament.last_matchday_of_group_stage : params[:matchday]
      @rankings = rankings.where('group_number IS NOT NULL AND matchday = ?', groups_matchday).order('group_number ASC').group_by(&:group_number)
      @rankings[:global] = rankings.where('group_number IS NULL AND matchday = ?', params[:matchday])
    else
      @rankings = @season.rankings.where('matchday = ?', params[:matchday]).order('position ASC')
    end
    
    render partial: ranking_collection_partial, layout: false if request.xhr?
  end
  
  def ranking_collection_partial
    "competition/rankings/#{@season.tournament.with_group_stage? ? 'global_and_group_collections' : 'collection'}"
  end
  
  helper_method :ranking_collection_partial
  
  def resource
    @ranking
  end
end

app/controllers/competition/season_participations_controller.rb
class Competition::SeasonParticipationsController < ::Competition::ApplicationController
  include ::Competition::BaseController
  include Applicat::Mvc::Controller::Resource
  
  load_and_authorize_resource class: 'TournamentSeasonParticipation'
  
  def new
    @season = TournamentSeason.find(params[:season_id])
    @season_participation = TournamentSeasonParticipation.new
    find_competitors
    
    params[:season_participation] ||= {}
    params[:season_participation][:competitor_ids] ||= @season.participations.where(competitor_id: @competitors.map(&:id)).map(&:competitor_id)
    
    render layout: false if request.xhr?
  end
  
  def index
    @season = TournamentSeason.find(params[:season_id])
    @season_participations = @season.participations.order_by_state.paginate(per_page: 25, page: params[:page] || 1)
    render partial: 'competition/season_participations/collection', layout: false if request.xhr?
  end
  
  def create
    params[:season_participation] ||= {}
    @season = TournamentSeason.find(params[:season_id])
    @season_participation = current_user.join_tournament_season_with_competitors(@season, params[:season_participation][:competitor_ids])
    
    if @season_participation.errors.any?
      find_competitors
    else
      @season_participations = @season.participations.order_by_state.paginate(per_page: 25, page: params[:page] || 1)
    end
    
    render layout: false if request.xhr?
  end
  
  def accept
    @season_participation.accept
    
    render layout: false
  end
  
  def deny
    @season_participation.deny
    
    render layout: false
  end
  
  private
  
  def find_competitors
    @competitors = current_user.competitors.where(game_and_exercise_type_id: @season.tournament.game_and_exercise_type_id).order('name')    
  end
end

app/controllers/competition/seasons_controller.rb
class Competition::SeasonsController < ::Competition::ApplicationController
  include ::Competition::BaseController
  include Applicat::Mvc::Controller::Resource
  include ::Competition::Bracket
  
  load_and_authorize_resource class: 'TournamentSeason', except: [:bracket]
  
  def bracket
    @season = TournamentSeason.find(params[:id])
    @can_update_season = can?(:update, @season)
    get_bracket_variables if @season.active?

    options = request.xhr? ? { layout: false } : {}
    render 'competition/tournament_seasons/bracket', options
  end
  
  def resource
    @season
  end
end

app/controllers/competition/tournaments_controller.rb
class Competition::TournamentsController < ::Competition::ApplicationController
  include ::Competition::BaseController
  include Applicat::Mvc::Controller::Resource
  
  load_and_authorize_resource
  
  rescue_from ActiveRecord::RecordNotFound, with: :not_found
  
  respond_to :html
  
  def index
  end
  
  def show
    @tournament = Tournament.find(params[:id])
    @seasons = @tournament.seasons.order('tournament_seasons.created_at DESC')
    @season = @seasons.find(params[:season_id] || @tournament.current_season_id)
    @matchday = params[:matchday] || @tournament.current_season.current_matchday
    @matchday = @matchday.to_i
    @ranking_matchday = @matchday > @tournament.current_season.current_matchday ? @tournament.current_season.current_matchday : @matchday
  end
  
  def new
    @tournament = current_user.tournaments.new(params[:tournament])
  end
  
  def create
    @tournament = current_user.tournaments.new(params[:tournament])
    
    if @tournament.save
      redirect_to [:competition, @tournament], notice: t('general.form.successfully_created')
    else
      render :new
    end
  end
  
  def edit
  end
  
  def update
    if @tournament.update_attributes(params[:tournament])
      redirect_to [:competition, @tournament], notice: t('general.form.successfully_updated')
    else
      render :edit
    end
  end

  def destroy
    @tournament.destroy
    redirect_to competition_tournaments_path, notice: t('general.form.destroyed')
  end
  
  def resource
    @tournament
  end
  
  private
  
  def not_found
    redirect_to competition_tournaments_path, notice: t('general.exceptions.not_found')
  end
end

app/controllers/concerns/competition/base_controller.rb
module Competition
  module BaseController
    extend ActiveSupport::Concern
      
    def application_navigation
      :main_competition
    end
    
    def navigation_product_path
      competition_product_path
    end
    
    def navigation_product_name
      'Competition'
    end
  end
end

app/controllers/concerns/competition/bracket.rb
module Competition
  module Bracket
    extend ActiveSupport::Concern
    
    def get_bracket_variables
      @is_single_elimination = @season.tournament.is_single_elimination?
      @is_double_elimination = @season.tournament.is_double_elimination?
      @winner_rounds = @season.winner_rounds
      @loser_rounds = @season.loser_rounds
      @with_second_leg = @season.tournament.with_second_leg?
      @third_place_playoff = @season.tournament.third_place_playoff?
      @matches, @round_matches_index = @season.elimination_stage_matches
    end
  end
end

app/controllers/product/competition_controller.rb
class Product::CompetitionController < ApplicationController
  include ::Competition::BaseController
  
  def index
  end
end

app/views/competition/season_participations/_actions.html.erb
<% if season_participation.can_accept? %>
  <%= link_to accept_competition_season_participation_path(season_participation.id), method: :put, remote: true, class: 'btn btn-danger change_state_of_season_participation_link' do %>
    <%= t('season_participations.general.events.accept') %> <%= image_tag 'voluntary/spinner.gif', class: 'ajax_spinner hide' %>
  <% end %>
<% end %>
<% if season_participation.can_deny? %>
  <%= link_to deny_competition_season_participation_path(season_participation.id), method: :put, remote: true, class: 'btn btn-danger change_state_of_season_participation_link' do %>
    <%= t('season_participations.general.events.deny') %> <%= image_tag 'voluntary/spinner.gif', class: 'ajax_spinner hide' %>
  <% end %>
<% end %>

app/views/competition/season_participations/_collection.html.erb
<% if @season_participations.none? %>
<p><%= I18n.t('season_participations.index.empty_collection')%></p>
<% else %>
  <table class="table table-striped">
    <thead>
      <tr class="<%= cycle('odd', 'even') %>">
        <th><%= t('activerecord.models.competitor') %></th>  
        <th><%= t('attributes.state') %></th>
      </tr>
    </thead>
    <tbody>
    <% @season_participations.each do |season_participation| %>
      <tr class="<%= cycle('odd', 'even') %>">
        <td><%= link_to season_participation.competitor.name, competition_competitor_path(season_participation.competitor) %></td>
        <td id="season_participation_<%= season_participation.id %>_state"><%= t("season_participations.general.states.#{season_participation.state}") %></td>
        <td id="season_participation_<%= season_participation.id %>_actions">
          <%= render partial: 'competition/season_participations/actions', locals: { season_participation: season_participation } %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% end %>

<%= will_paginate @season_participations %>

app/views/competition/season_participations/_form.html.erb
<% content_for :modal_body do %>
  <%= render partial: 'shared/form/error_messages', locals: { resource: @season_participation } %>

  <%= render partial: 'shared/layouts/twitter_bootstrap/control_group', locals: { 
    required: true, label: t('activerecord.attributes.tournament_season_participation.competitor_ids'),
    field: select_tag(
      'season_participation[competitor_ids]', options_for_select(
        @competitors.map{|c| [c.name, c.id]}, params[:season_participation][:competitor_ids]
      ), 
      multiple: true
    )
  } %>
<% end %>
<% content_for :modal_footer do %>
  <%= submit_tag t('general.submit') %>
<% end %>
<%= form_tag competition_season_participations_path(@season), method: :post, remote: true, class: 'simple_form form-horizontal' do %>
  <%= render partial: 'shared/layouts/twitter_bootstrap/modal', locals: { title: t('season_participations.new.title') } %>
<% end %>

app/views/competition/season_participations/accept.js.erb
<% if @season_participation.accepted? %>
  $('#season_participation_<%= @season_participation.id %>_state').html("<%= t("season_participations.general.states.#{@season_participation.state}") %>");
<% else %>
  alert("<%= I18n.t('season_participations.accept.failed', errors: @season_participation.errors.full_messages.join('. '))%>");
<% end %>

$('#season_participation_<%= @season_participation.id %>_actions').html('<%= escape_javascript render(partial: 'competition/season_participations/actions', locals: { season_participation: @season_participation }) %>');

app/views/competition/season_participations/create.js.erb
<% if @season_participation.errors.any? %>
  $('#tournament_season_form').html('<%= escape_javascript render(partial: 'competition/season_participations/form') %>');
<% else %>
  $('#season_participation').html('<%= escape_javascript render(partial: 'competition/tournament_seasons/join_or_leave') %>');
  participantsTabAnchorId = $('.ui-tabs-anchor:contains("<%= t('season_participations.index.short_title') %>")').prop('id')
  
  if(participantsTabAnchorId != undefined) {
    $('#ui-tabs-' + participantsTabAnchorId.split('-')[2]).html('<%= escape_javascript render(partial: 'competition/season_participations/collection') %>');
  }
  
  $('#bootstrap_modal').modal('hide');
<% end %>

app/views/competition/season_participations/deny.js.erb
<% if @season_participation.denied? %>
  $('#season_participation_<%= @season_participation.id %>_state').html("<%= t("season_participations.general.states.#{@season_participation.state}") %>");
<% else %>
  alert("<%= I18n.t('season_participations.deny.failed', errors: @season_participation.errors.full_messages.join('. '))%>");
<% end %>

$('#season_participation_<%= @season_participation.id %>_actions').html('<%= escape_javascript render(partial: 'competition/season_participations/actions', locals: { season_participation: @season_participation }) %>');

app/views/competition/season_participations/new.html.erb
<div id="tournament_season_form">
  <%= render partial: 'competition/season_participations/form' %>
</div>