config/routes.rb
Rails.application.routes.draw do
  get '/products/competition', to: redirect('/competition'), as: 'competition_product'
  get '/competition' => 'product/competition#index'
  
  namespace :competition do
    resources :games
    resources :exercise_types
    resources :tournaments
    
    resources :seasons, only: [] do
      resources :participations, controller: 'season_participations', only: [:index, :new, :create] 
      resources :rankings, only: [:index]
      
      resources :matches, only: [:index] do
        collection do
          put :updates
        end
      end
      
      member do
        get :bracket
      end
    end
    
    resources :season_participations, only: [] do
      member do
        put :accept
        put :deny
      end
    end
    
    resources :competitors
    resources :matches, only: [:show]
  end
end

app/models/product/competition.rb
class Product::Competition < ::Product
end

app/models/tournament.rb
class Tournament < ActiveRecord::Base
  include Applicat::Mvc::Model::Resource::Base
  include GameAndExerciseTypeAssociation
  
  SYSTEM_TYPES = %w(round_robin single_elimination double_elimination)
  
  belongs_to :game_and_exercise_type
  belongs_to :user
  belongs_to :current_season, class_name: 'TournamentSeason'
  
  has_many :seasons, class_name: 'TournamentSeason', dependent: :destroy
  
  validates :game_and_exercise_type_id, presence: true
  validates :system_type, presence: true, inclusion: { in: SYSTEM_TYPES.length.times.to_a }
  validate :system_type_requirements
  validates :user_id, presence: true
  validates :name, presence: true, uniqueness: { case_sensitive: false, scope: [:user_id, :game_and_exercise_type_id] }
  validates :competitors_limit, presence: true, numericality: { only_integer: true }
  validates :groups_count, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 2 }, if: 'with_group_stage?'
  
  attr_accessible :system_type, :name, :with_second_leg, :with_group_stage, :groups_count, :third_place_playoff, :first_season_name, :competitors_limit
  
  attr_accessor :first_season_name
  
  before_validation :reset_elimination_attributes_if_attributes_are_not_compatible_with_system_type
  after_create :create_first_season
  
  def is_round_robin?
    system_type == 0
  end
  
  def is_single_elimination?
    system_type == 1
  end
  
  def is_double_elimination?
    system_type == 2
  end
  
  def is_elimination?
    is_single_elimination? || is_double_elimination?
  end
  
  def competitors_per_group
    competitors_limit / groups_count
  end
  
  def last_matchday_of_group_stage
    first_leg_matchdays_count = competitors_per_group % 2 == 0 ? (competitors_per_group - 1) : competitors_per_group
    with_second_leg? ? (first_leg_matchdays_count * 2) : first_leg_matchdays_count
  end
  
  def elimination_stage_competitors_count
    with_group_stage? ? groups_count * 2 : competitors_limit
  end
    
  private
  
  def reset_elimination_attributes_if_attributes_are_not_compatible_with_system_type
    self.with_group_stage = false if is_round_robin?
    self.groups_count = nil if is_round_robin?
    self.third_place_playoff = false if is_round_robin? || is_double_elimination?
    
    return true
  end
  
  def system_type_requirements
    case system_type
    when 1
      unless (with_group_stage? && groups_count.blank?) || (elimination_stage_competitors_count & (elimination_stage_competitors_count - 1) == 0)
        errors[:competitors_limit] << I18n.t('activerecord.errors.models.tournament.attributes.system_type.competitors_limit_must_be_power_of_two')
      end
      
      if competitors_limit < 4
        errors[:competitors_limit] << I18n.t('activerecord.errors.models.tournament.attributes.system_type.competitors_limit_should_be_at_least_4')
      end
      
      if with_group_stage?
        if competitors_limit % groups_count != 0
          errors[:groups_count] << I18n.t('activerecord.errors.models.tournament.attributes.system_type.groups_count_invalid')
        elsif competitors_per_group < 3
          errors[:groups_count] << I18n.t('activerecord.errors.models.tournament.attributes.system_type.groups_with_at_least_3_competitors')
        end
      end
    end
  end
  
  def create_first_season
    update_attribute(:current_season_id, seasons.create!(name: first_season_name).id)
  end
end

app/controllers/competition/application_controller.rb
class Competition::ApplicationController < ::ApplicationController
  protected

  def voluntary_application_stylesheets
    ['voluntary/application', 'application'] 
  end

  def voluntary_application_javascripts
    ['voluntary/application', 'voluntary_competition/application', 'application'] 
  end
end

app/controllers/competition/competitors_controller.rb
class Competition::CompetitorsController < ::Competition::ApplicationController
  include ::Competition::BaseController
  include Applicat::Mvc::Controller::Resource
  
  load_and_authorize_resource
  
  rescue_from ActiveRecord::RecordNotFound, with: :not_found
  
  respond_to :html
  
  def index
  end
  
  def show
  end
  
  def new
    @competitor = current_user.competitors.new(params[:competitor])
  end
  
  def create
    @competitor = current_user.competitors.new(params[:competitor])
    
    if @competitor.save
      redirect_to [:competition, @competitor], notice: t('general.form.successfully_created')
    else
      render :new
    end
  end
  
  def edit
  end
  
  def update
    if @competitor.update_attributes(params[:competitor])
      redirect_to [:competition, @competitor], notice: t('general.form.successfully_updated')
    else
      render :edit
    end
  end

  def destroy
    @competitor.destroy
    redirect_to competition_competitors_path, notice: t('general.form.destroyed')
  end
  
  def resource
    @competitor
  end
  
  private
  
  def not_found
    redirect_to competition_competitors_path, notice: t('general.exceptions.not_found')
  end
end

app/controllers/competition/exercise_types_controller.rb
class Competition::ExerciseTypesController < ::Competition::ApplicationController
  include ::Competition::BaseController
  include Applicat::Mvc::Controller::Resource
  
  load_and_authorize_resource
  
  rescue_from ActiveRecord::RecordNotFound, with: :not_found
  
  respond_to :html
  
  def index
  end
  
  def show
    @exercise_type = ExerciseType.find(params[:id])
  end
  
  def new
    @exercise_type = ExerciseType.new(params[:exercise_type])
  end
  
  def create
    @exercise_type = ExerciseType.new(params[:exercise_type])
    
    if @exercise_type.save
      redirect_to [:competition, @exercise_type], notice: t('general.form.successfully_created')
    else
      render :new
    end
  end
  
  def edit
  end
  
  def update
    if @exercise_type.update_attributes(params[:exercise_type])
      redirect_to [:competition, @exercise_type], notice: t('general.form.successfully_updated')
    else
      render :edit
    end
  end

  def destroy
    @exercise_type.destroy
    redirect_to competition_exercise_types_path, notice: t('general.form.destroyed')
  end
  
  def resource
    @exercise_type
  end
  
  private
  
  def not_found
    redirect_to competition_exercise_types_path, notice: t('general.exceptions.not_found')
  end
end

app/controllers/competition/games_controller.rb
class Competition::GamesController < ::Competition::ApplicationController
  include ::Competition::BaseController
  include Applicat::Mvc::Controller::Resource
  
  load_and_authorize_resource
  
  rescue_from ActiveRecord::RecordNotFound, with: :not_found
  
  respond_to :html
  
  def index
  end
  
  def show
    @game = Game.find(params[:id])
  end
  
  def new
    @game = Game.new(params[:game])
  end
  
  def create
    @game = Game.new(params[:game])
    
    if @game.save
      redirect_to [:competition, @game], notice: t('general.form.successfully_created')
    else
      render :new
    end
  end
  
  def edit
  end
  
  def update
    if @game.update_attributes(params[:game])
      redirect_to [:competition, @game], notice: t('general.form.successfully_updated')
    else
      render :edit
    end
  end

  def destroy
    @game.destroy
    redirect_to competition_games_path, notice: t('general.form.destroyed')
  end
  
  def resource
    @game
  end
  
  private
  
  def not_found
    redirect_to competition_games_path, notice: t('general.exceptions.not_found')
  end
end

app/controllers/competition/matches_controller.rb
class Competition::MatchesController < ::Competition::ApplicationController
  include ::Competition::BaseController
  include Applicat::Mvc::Controller::Resource
  include ::Competition::Bracket
  
  load_and_authorize_resource class: 'TournamentMatch'
  
  def index
    @season = TournamentSeason.find(params[:season_id])
    @can_update_season = can?(:update, @season)
    @matches = @season.matches.where('matchday = ?', params[:matchday])
    render partial: 'competition/matches/collection', layout: false if request.xhr?
  end
  
  def updates
    @season = TournamentSeason.find(params[:season_id])
    @can_update_season = can?(:update, @season)
    
    if params[:matches].present?
      @input_matches = @season.consider_matches(params[:matches], params[:matchday])
    else
      @input_matches = []
    end
    
    unless params[:from_bracket].blank? || @input_matches.empty? || @input_matches.select{ |m| !m.errors.empty? }.any?
      @season.reload
      get_bracket_variables
    end
     
    render layout: false if request.xhr?
  end
end

app/controllers/competition/rankings_controller.rb
class Competition::RankingsController < ::Competition::ApplicationController
  include ::Competition::BaseController
  include Applicat::Mvc::Controller::Resource
  
  load_and_authorize_resource class: 'TournamentSeasonRanking'
  
  def index
    @season = TournamentSeason.find(params[:season_id])
    
    if @season.tournament.with_group_stage?
      rankings = @season.rankings.order('position ASC')
      groups_matchday = params[:matchday].to_i > @season.tournament.last_matchday_of_group_stage ? @season.tournament.last_matchday_of_group_stage : params[:matchday]
      @rankings = rankings.where('group_number IS NOT NULL AND matchday = ?', groups_matchday).order('group_number ASC').group_by(&:group_number)
      @rankings[:global] = rankings.where('group_number IS NULL AND matchday = ?', params[:matchday])
    else
      @rankings = @season.rankings.where('matchday = ?', params[:matchday]).order('position ASC')
    end
    
    render partial: ranking_collection_partial, layout: false if request.xhr?
  end
  
  def ranking_collection_partial
    "competition/rankings/#{@season.tournament.with_group_stage? ? 'global_and_group_collections' : 'collection'}"
  end
  
  helper_method :ranking_collection_partial
  
  def resource
    @ranking
  end
end

app/controllers/competition/season_participations_controller.rb
class Competition::SeasonParticipationsController < ::Competition::ApplicationController
  include ::Competition::BaseController
  include Applicat::Mvc::Controller::Resource
  
  load_and_authorize_resource class: 'TournamentSeasonParticipation'
  
  def new
    @season = TournamentSeason.find(params[:season_id])
    @season_participation = TournamentSeasonParticipation.new
    find_competitors
    
    params[:season_participation] ||= {}
    params[:season_participation][:competitor_ids] ||= @season.participations.where(competitor_id: @competitors.map(&:id)).map(&:competitor_id)
    
    render layout: false if request.xhr?
  end
  
  def index
    @season = TournamentSeason.find(params[:season_id])
    @season_participations = @season.participations.order_by_state.paginate(per_page: 25, page: params[:page] || 1)
    render partial: 'competition/season_participations/collection', layout: false if request.xhr?
  end
  
  def create
    params[:season_participation] ||= {}
    @season = TournamentSeason.find(params[:season_id])
    @season_participation = current_user.join_tournament_season_with_competitors(@season, params[:season_participation][:competitor_ids])
    
    if @season_participation.errors.any?
      find_competitors
    else
      @season_participations = @season.participations.order_by_state.paginate(per_page: 25, page: params[:page] || 1)
    end
    
    render layout: false if request.xhr?
  end
  
  def accept
    @season_participation.accept
    
    render layout: false
  end
  
  def deny
    @season_participation.deny
    
    render layout: false
  end
  
  private
  
  def find_competitors
    @competitors = current_user.competitors.where(game_and_exercise_type_id: @season.tournament.game_and_exercise_type_id).order('name')    
  end
end

app/controllers/competition/seasons_controller.rb
class Competition::SeasonsController < ::Competition::ApplicationController
  include ::Competition::BaseController
  include Applicat::Mvc::Controller::Resource
  include ::Competition::Bracket
  
  load_and_authorize_resource class: 'TournamentSeason', except: [:bracket]
  
  def bracket
    @season = TournamentSeason.find(params[:id])
    @can_update_season = can?(:update, @season)
    get_bracket_variables if @season.active?

    options = request.xhr? ? { layout: false } : {}
    render 'competition/tournament_seasons/bracket', options
  end
  
  def resource
    @season
  end
end

app/controllers/competition/tournaments_controller.rb
class Competition::TournamentsController < ::Competition::ApplicationController
  include ::Competition::BaseController
  include Applicat::Mvc::Controller::Resource
  
  load_and_authorize_resource
  
  rescue_from ActiveRecord::RecordNotFound, with: :not_found
  
  respond_to :html
  
  def index
  end
  
  def show
    @tournament = Tournament.find(params[:id])
    @seasons = @tournament.seasons.order('tournament_seasons.created_at DESC')
    @season = @seasons.find(params[:season_id] || @tournament.current_season_id)
    @matchday = params[:matchday] || @tournament.current_season.current_matchday
    @matchday = @matchday.to_i
    @ranking_matchday = @matchday > @tournament.current_season.current_matchday ? @tournament.current_season.current_matchday : @matchday
  end
  
  def new
    @tournament = current_user.tournaments.new(params[:tournament])
  end
  
  def create
    @tournament = current_user.tournaments.new(params[:tournament])
    
    if @tournament.save
      redirect_to [:competition, @tournament], notice: t('general.form.successfully_created')
    else
      render :new
    end
  end
  
  def edit
  end
  
  def update
    if @tournament.update_attributes(params[:tournament])
      redirect_to [:competition, @tournament], notice: t('general.form.successfully_updated')
    else
      render :edit
    end
  end

  def destroy
    @tournament.destroy
    redirect_to competition_tournaments_path, notice: t('general.form.destroyed')
  end
  
  def resource
    @tournament
  end
  
  private
  
  def not_found
    redirect_to competition_tournaments_path, notice: t('general.exceptions.not_found')
  end
end

app/controllers/concerns/competition/base_controller.rb
module Competition
  module BaseController
    extend ActiveSupport::Concern
      
    def application_navigation
      :main_competition
    end
    
    def navigation_product_path
      competition_product_path
    end
    
    def navigation_product_name
      'Competition'
    end
  end
end

app/controllers/concerns/competition/bracket.rb
module Competition
  module Bracket
    extend ActiveSupport::Concern
    
    def get_bracket_variables
      @is_single_elimination = @season.tournament.is_single_elimination?
      @is_double_elimination = @season.tournament.is_double_elimination?
      @winner_rounds = @season.winner_rounds
      @loser_rounds = @season.loser_rounds
      @with_second_leg = @season.tournament.with_second_leg?
      @third_place_playoff = @season.tournament.third_place_playoff?
      @matches, @round_matches_index = @season.elimination_stage_matches
    end
  end
end

app/controllers/product/competition_controller.rb
class Product::CompetitionController < ApplicationController
  include ::Competition::BaseController
  
  def index
  end
end

app/views/competition/tournaments/_form.html.erb
<%= simple_form_for([:competition, @tournament], html: {class: 'form-horizontal'}) do |f| %>
  <%= render partial: 'shared/form/error_messages', locals: { resource: @tournament } %>

  <%= render partial: 'shared/game_and_exercise_type_association', locals: { f: f } %>
  <%= f.input :system_type, as: :radio_buttons, collection: Tournament::SYSTEM_TYPES.each_with_index.map { |x,i| [x.titleize, i] } if f.object.new_record? %>
  <%= f.input :name %>
  
  <% if f.object.new_record? %>
  <%= f.input :competitors_limit %>
  <%= f.input :with_second_leg %>
  <div id="tournament_with_group_stage_wrapper" style="display: <%= @tournament.is_round_robin? ? 'none' : 'block' %>;">
    <%= f.input :with_group_stage %>
  </div>
  <div id="tournament_groups_count_wrapper" style="display: <%= @tournament.is_round_robin? ? 'none' : 'block' %>;">
    <%= f.input :groups_count %>
  </div>
  <div id="tournament_third_place_playoff_wrapper" style="display: <%= @tournament.is_round_robin? ? 'none' : 'block' %>;">
    <%= f.input :third_place_playoff %>
  </div>
  <%= f.input :first_season_name %>
  <% end %>
  
  <div class="form-group">
    <div class="col-sm-offset-3 col-sm-9">
      <%= f.button :submit %>
    </div>
  </div>
<% end %>

app/views/competition/tournaments/edit.html.erb
<h3><%= t('tournaments.edit.title') %></h3>

<%= render 'form' %>

app/views/competition/tournaments/new.html.erb
<h3><%= t('tournaments.new.title') %></h3>

<%= render 'form' %>

<% content_for :javascript_includes do %>
  <%= javascript_include_tag 'voluntary_competition/tournaments/new' %>
<% end %>

app/views/competition/tournaments/show.html.erb
<h3>
  <a name="top">&nbsp;</a>
  <%= @tournament.name %>
</h3>

<dl class="dl-horizontal">
  <%= show_attribute :exercise_type_id, value: link_to(@tournament.game_and_exercise_type.exercise_type.name, competition_exercise_type_path(@tournament.game_and_exercise_type.exercise_type.id)) %>
  <%= show_attribute :game_id, value: link_to(@tournament.game_and_exercise_type.game.name, competition_game_path(@tournament.game_and_exercise_type.game.id)) %>
  <%= show_actions namespace: :competition %>
</dl>

<table>
  <tr>
    <td style="width:270px">
      <%= form_tag competition_tournament_path(@tournament), method: :get, class: 'simple_form form-horizontal' do %>
        <label for="season_id" class="string required" style="display:inline"><%= t('tournament_seasons.general.short_model_name') %></label>&nbsp;&nbsp;
        <%= hidden_field_tag 'matchday', @matchday %>
        <%= select_tag 'season_id', options_for_select(@seasons.map{|s| [s.name.blank? ? s.id : s.name, s.id]}, @season.id), style: 'width:110px' %> 
        <% if @season.looking_for_competitors? && user_signed_in? %>
          &nbsp;&nbsp;
          <div id="season_participation" style="display:inline;"><%= render partial: 'competition/tournament_seasons/join_or_leave' %></div>
        <% end %>
      <% end %>
    </td>
<% if @season.matchdays.to_i > 0 %>
    <td>
      <%= form_tag competition_tournament_path(@tournament), method: :get, class: 'simple_form form-horizontal' do %>
        <label for="matchday" class="string required" style="display:inline"><%= t('activerecord.attributes.tournament_match.matchday') %></label>&nbsp;&nbsp;
        <%= hidden_field_tag 'season_id', @season.id %>
        <%= select_tag 'matchday', options_for_select((1..@season.matchdays).to_a, @matchday), style: 'width:50px' %> 
      <% end %>
    </td>
<% end %>
  </tr>
</table>

<div class="tabs tournament_show_tabs">
  <ul>
    <li>
      <a href="<%= competition_season_rankings_path(@season.id, matchday: @ranking_matchday) %>">
        <%= t('tournament_season_rankings.index.title') %>
      </a>
    </li>
    <li>
      <a href="<%= competition_season_matches_path(@season.id, matchday: @matchday) %>">
        <%= t('tournament_matches.index.title') %>
        <%= image_tag 'voluntary/spinner.gif', class: 'ajax_spinner hide' %>
      </a>
    </li>
    <li>
      <a href="<%= bracket_competition_season_path(@season.id) %>">
        <%= t('tournament_seasons.bracket.title') %>
        <%= image_tag 'voluntary/spinner.gif', class: 'ajax_spinner hide' %>
      </a>
    </li>
<% if can? :update, @season %>
    <li>
      <a href="<%= competition_season_participations_path(@season.id) %>">
        <%= t('season_participations.index.short_title') %> 
        <%= image_tag 'voluntary/spinner.gif', class: 'ajax_spinner hide' %>
      </a>
    </li>
<% end %>
  </ul>
</div>

<% javascript_tag do %>
  matchday = <%= @matchday %>
<% end %>
<% content_for :javascript_includes do %>
  <%= javascript_include_tag 'voluntary_competition/tournaments/show' %>
<% end %>