config/routes.rb
Rails.application.routes.draw do
  get '/products/competition', to: redirect('/competition'), as: 'competition_product'
  get '/competition' => 'product/competition#index'
  
  namespace :competition do
    resources :games
    resources :exercise_types
    resources :tournaments
    
    resources :seasons, only: [] do
      resources :participations, controller: 'season_participations', only: [:index, :new, :create] 
      resources :rankings, only: [:index]
      
      resources :matches, only: [:index] do
        collection do
          put :updates
        end
      end
      
      member do
        get :bracket
      end
    end
    
    resources :season_participations, only: [] do
      member do
        put :accept
        put :deny
      end
    end
    
    resources :competitors
    resources :matches, only: [:show]
  end
end

app/models/product/competition.rb
class Product::Competition < ::Product
end

app/controllers/competition/application_controller.rb
class Competition::ApplicationController < ::ApplicationController
  protected

  def voluntary_application_stylesheets
    ['voluntary/application', 'application'] 
  end

  def voluntary_application_javascripts
    ['voluntary/application', 'voluntary_competition/application', 'application'] 
  end
end

app/controllers/competition/competitors_controller.rb
class Competition::CompetitorsController < ::Competition::ApplicationController
  include ::Competition::BaseController
  include Applicat::Mvc::Controller::Resource
  
  load_and_authorize_resource
  
  rescue_from ActiveRecord::RecordNotFound, with: :not_found
  
  respond_to :html
  
  def index
  end
  
  def show
  end
  
  def new
    @competitor = current_user.competitors.new(params[:competitor])
  end
  
  def create
    @competitor = current_user.competitors.new(params[:competitor])
    
    if @competitor.save
      redirect_to [:competition, @competitor], notice: t('general.form.successfully_created')
    else
      render :new
    end
  end
  
  def edit
  end
  
  def update
    if @competitor.update_attributes(params[:competitor])
      redirect_to [:competition, @competitor], notice: t('general.form.successfully_updated')
    else
      render :edit
    end
  end

  def destroy
    @competitor.destroy
    redirect_to competition_competitors_path, notice: t('general.form.destroyed')
  end
  
  def resource
    @competitor
  end
  
  private
  
  def not_found
    redirect_to competition_competitors_path, notice: t('general.exceptions.not_found')
  end
end

app/controllers/competition/exercise_types_controller.rb
class Competition::ExerciseTypesController < ::Competition::ApplicationController
  include ::Competition::BaseController
  include Applicat::Mvc::Controller::Resource
  
  load_and_authorize_resource
  
  rescue_from ActiveRecord::RecordNotFound, with: :not_found
  
  respond_to :html
  
  def index
  end
  
  def show
    @exercise_type = ExerciseType.find(params[:id])
  end
  
  def new
    @exercise_type = ExerciseType.new(params[:exercise_type])
  end
  
  def create
    @exercise_type = ExerciseType.new(params[:exercise_type])
    
    if @exercise_type.save
      redirect_to [:competition, @exercise_type], notice: t('general.form.successfully_created')
    else
      render :new
    end
  end
  
  def edit
  end
  
  def update
    if @exercise_type.update_attributes(params[:exercise_type])
      redirect_to [:competition, @exercise_type], notice: t('general.form.successfully_updated')
    else
      render :edit
    end
  end

  def destroy
    @exercise_type.destroy
    redirect_to competition_exercise_types_path, notice: t('general.form.destroyed')
  end
  
  def resource
    @exercise_type
  end
  
  private
  
  def not_found
    redirect_to competition_exercise_types_path, notice: t('general.exceptions.not_found')
  end
end

app/controllers/competition/games_controller.rb
class Competition::GamesController < ::Competition::ApplicationController
  include ::Competition::BaseController
  include Applicat::Mvc::Controller::Resource
  
  load_and_authorize_resource
  
  rescue_from ActiveRecord::RecordNotFound, with: :not_found
  
  respond_to :html
  
  def index
  end
  
  def show
    @game = Game.find(params[:id])
  end
  
  def new
    @game = Game.new(params[:game])
  end
  
  def create
    @game = Game.new(params[:game])
    
    if @game.save
      redirect_to [:competition, @game], notice: t('general.form.successfully_created')
    else
      render :new
    end
  end
  
  def edit
  end
  
  def update
    if @game.update_attributes(params[:game])
      redirect_to [:competition, @game], notice: t('general.form.successfully_updated')
    else
      render :edit
    end
  end

  def destroy
    @game.destroy
    redirect_to competition_games_path, notice: t('general.form.destroyed')
  end
  
  def resource
    @game
  end
  
  private
  
  def not_found
    redirect_to competition_games_path, notice: t('general.exceptions.not_found')
  end
end

app/controllers/competition/matches_controller.rb
class Competition::MatchesController < ::Competition::ApplicationController
  include ::Competition::BaseController
  include Applicat::Mvc::Controller::Resource
  include ::Competition::Bracket
  
  load_and_authorize_resource class: 'TournamentMatch'
  
  def index
    @season = TournamentSeason.find(params[:season_id])
    @can_update_season = can?(:update, @season)
    @matches = @season.matches.where('matchday = ?', params[:matchday])
    render partial: 'competition/matches/collection', layout: false if request.xhr?
  end
  
  def updates
    @season = TournamentSeason.find(params[:season_id])
    @can_update_season = can?(:update, @season)
    
    if params[:matches].present?
      @input_matches = @season.consider_matches(params[:matches], params[:matchday])
    else
      @input_matches = []
    end
    
    unless params[:from_bracket].blank? || @input_matches.empty? || @input_matches.select{ |m| !m.errors.empty? }.any?
      @season.reload
      get_bracket_variables
    end
     
    render layout: false if request.xhr?
  end
end

app/controllers/competition/rankings_controller.rb
class Competition::RankingsController < ::Competition::ApplicationController
  include ::Competition::BaseController
  include Applicat::Mvc::Controller::Resource
  
  load_and_authorize_resource class: 'TournamentSeasonRanking'
  
  def index
    @season = TournamentSeason.find(params[:season_id])
    
    if @season.tournament.with_group_stage?
      rankings = @season.rankings.order('position ASC')
      groups_matchday = params[:matchday].to_i > @season.tournament.last_matchday_of_group_stage ? @season.tournament.last_matchday_of_group_stage : params[:matchday]
      @rankings = rankings.where('group_number IS NOT NULL AND matchday = ?', groups_matchday).order('group_number ASC').group_by(&:group_number)
      @rankings[:global] = rankings.where('group_number IS NULL AND matchday = ?', params[:matchday])
    else
      @rankings = @season.rankings.where('matchday = ?', params[:matchday]).order('position ASC')
    end
    
    render partial: ranking_collection_partial, layout: false if request.xhr?
  end
  
  def ranking_collection_partial
    "competition/rankings/#{@season.tournament.with_group_stage? ? 'global_and_group_collections' : 'collection'}"
  end
  
  helper_method :ranking_collection_partial
  
  def resource
    @ranking
  end
end

app/controllers/competition/season_participations_controller.rb
class Competition::SeasonParticipationsController < ::Competition::ApplicationController
  include ::Competition::BaseController
  include Applicat::Mvc::Controller::Resource
  
  load_and_authorize_resource class: 'TournamentSeasonParticipation'
  
  def new
    @season = TournamentSeason.find(params[:season_id])
    @season_participation = TournamentSeasonParticipation.new
    find_competitors
    
    params[:season_participation] ||= {}
    params[:season_participation][:competitor_ids] ||= @season.participations.where(competitor_id: @competitors.map(&:id)).map(&:competitor_id)
    
    render layout: false if request.xhr?
  end
  
  def index
    @season = TournamentSeason.find(params[:season_id])
    @season_participations = @season.participations.order_by_state.paginate(per_page: 25, page: params[:page] || 1)
    render partial: 'competition/season_participations/collection', layout: false if request.xhr?
  end
  
  def create
    params[:season_participation] ||= {}
    @season = TournamentSeason.find(params[:season_id])
    @season_participation = current_user.join_tournament_season_with_competitors(@season, params[:season_participation][:competitor_ids])
    
    if @season_participation.errors.any?
      find_competitors
    else
      @season_participations = @season.participations.order_by_state.paginate(per_page: 25, page: params[:page] || 1)
    end
    
    render layout: false if request.xhr?
  end
  
  def accept
    @season_participation.accept
    
    render layout: false
  end
  
  def deny
    @season_participation.deny
    
    render layout: false
  end
  
  private
  
  def find_competitors
    @competitors = current_user.competitors.where(game_and_exercise_type_id: @season.tournament.game_and_exercise_type_id).order('name')    
  end
end

app/controllers/competition/seasons_controller.rb
class Competition::SeasonsController < ::Competition::ApplicationController
  include ::Competition::BaseController
  include Applicat::Mvc::Controller::Resource
  include ::Competition::Bracket
  
  load_and_authorize_resource class: 'TournamentSeason', except: [:bracket]
  
  def bracket
    @season = TournamentSeason.find(params[:id])
    @can_update_season = can?(:update, @season)
    get_bracket_variables if @season.active?

    options = request.xhr? ? { layout: false } : {}
    render 'competition/tournament_seasons/bracket', options
  end
  
  def resource
    @season
  end
end

app/controllers/competition/tournaments_controller.rb
class Competition::TournamentsController < ::Competition::ApplicationController
  include ::Competition::BaseController
  include Applicat::Mvc::Controller::Resource
  
  load_and_authorize_resource
  
  rescue_from ActiveRecord::RecordNotFound, with: :not_found
  
  respond_to :html
  
  def index
  end
  
  def show
    @tournament = Tournament.find(params[:id])
    @seasons = @tournament.seasons.order('tournament_seasons.created_at DESC')
    @season = @seasons.find(params[:season_id] || @tournament.current_season_id)
    @matchday = params[:matchday] || @tournament.current_season.current_matchday
    @matchday = @matchday.to_i
    @ranking_matchday = @matchday > @tournament.current_season.current_matchday ? @tournament.current_season.current_matchday : @matchday
  end
  
  def new
    @tournament = current_user.tournaments.new(params[:tournament])
  end
  
  def create
    @tournament = current_user.tournaments.new(params[:tournament])
    
    if @tournament.save
      redirect_to [:competition, @tournament], notice: t('general.form.successfully_created')
    else
      render :new
    end
  end
  
  def edit
  end
  
  def update
    if @tournament.update_attributes(params[:tournament])
      redirect_to [:competition, @tournament], notice: t('general.form.successfully_updated')
    else
      render :edit
    end
  end

  def destroy
    @tournament.destroy
    redirect_to competition_tournaments_path, notice: t('general.form.destroyed')
  end
  
  def resource
    @tournament
  end
  
  private
  
  def not_found
    redirect_to competition_tournaments_path, notice: t('general.exceptions.not_found')
  end
end

app/controllers/concerns/competition/base_controller.rb
module Competition
  module BaseController
    extend ActiveSupport::Concern
      
    def application_navigation
      :main_competition
    end
    
    def navigation_product_path
      competition_product_path
    end
    
    def navigation_product_name
      'Competition'
    end
  end
end

app/controllers/concerns/competition/bracket.rb
module Competition
  module Bracket
    extend ActiveSupport::Concern
    
    def get_bracket_variables
      @is_single_elimination = @season.tournament.is_single_elimination?
      @is_double_elimination = @season.tournament.is_double_elimination?
      @winner_rounds = @season.winner_rounds
      @loser_rounds = @season.loser_rounds
      @with_second_leg = @season.tournament.with_second_leg?
      @third_place_playoff = @season.tournament.third_place_playoff?
      @matches, @round_matches_index = @season.elimination_stage_matches
    end
  end
end

app/controllers/product/competition_controller.rb
class Product::CompetitionController < ApplicationController
  include ::Competition::BaseController
  
  def index
  end
end

app/helpers/tournament_seasons_helper.rb
module TournamentSeasonsHelper
  def round_title(of_winners_bracket, round)
    rounds = of_winners_bracket ? @winner_rounds : (@loser_rounds - 1)
    index = rounds - round
    
    title = if of_winners_bracket && @is_single_elimination
      [
        t('tournament_seasons.general.rounds.final'), t('tournament_seasons.general.rounds.semi_final'),
        t('tournament_seasons.general.rounds.quarter_final'), t('tournament_seasons.general.rounds.round_of_16')
      ]
    elsif of_winners_bracket && @is_double_elimination
      [
        t('tournament_seasons.general.rounds.grand_finals'), t('tournament_seasons.general.rounds.winners_finals'), 
        t('tournament_seasons.general.rounds.semi_final'), t('tournament_seasons.general.rounds.quarter_final'), 
        t('tournament_seasons.general.rounds.round_of_16')
      ]
    else
      [t('tournament_seasons.general.rounds.losers_finals'), t('tournament_seasons.general.rounds.losers_semi_finals')]
    end[index] 
    
    return title unless title.blank?
    
    if of_winners_bracket
      "#{round.ordinalize} #{t('tournament_seasons.general.round')}"
    else
      "#{t('tournament_seasons.general.losers_round')} #{round}"
    end
  end
  
  def round_matches_for_competitors(of_winners_bracket, round, competitor_ids)
    return nil unless @matches[of_winners_bracket].has_key? round
    
    matches = []
    
    @matches[of_winners_bracket][round].keys.sort.each do |matchday|
      @matches[of_winners_bracket][round][matchday].each do |match|
        matches << match if competitor_ids.include?(match.home_competitor_id) && competitor_ids.include?(match.away_competitor_id)
      end
    end
    
    matches
  end
  
  def rowspan_for_round_connector(round)
    rowspan = 3
    round.times { rowspan *= 2 }
    rowspan
  end
  
  def match_for_round_after_first_one?(first_round_matches_index, round)
    first_round_matches_per_round_match = 1
    
    (round - 1).times do
      first_round_matches_per_round_match *= 2
    end
     
    # round 2: first_round_matches_per_round_match = 2 => 0, 2, 4
    # round 3: first_round_matches_per_round_match = 4 => 1, 5, 9
    # round 4: first_round_matches_per_round_match = 8 => 3, 11, 19
    # ...
    offset = (first_round_matches_per_round_match / 2) - 1
    
    begin
      if offset == first_round_matches_index
        return true
      end
      
      offset += first_round_matches_per_round_match
    end while offset <= first_round_matches_index
  
    return false
  end
  
  def first_round_matches_index_for_last_match_of_round(round)
    first_round_matches_index, index = 0, 0
    
    begin
      first_round_matches_index = index if match_for_round_after_first_one?(index, round)
      index += 1
    end while index < @matches[true][1][1].length
    
    first_round_matches_index
  end
end

app/views/competition/tournament_seasons/_bracket.html.erb
<%= form_tag updates_competition_season_matches_path(@season.id), method: :put, remote: true, id: 'bracket_matches_form' do %>
  <%= hidden_field_tag 'from_bracket', true %>
  <%= hidden_field_tag 'matchday', @season.current_matchday %>
  <table cellspacing="0" cellpadding="0" border="0" style="font-size:70%; margin:1em 2em 1em 1em; border-collapse: separate;">
    <tbody>
      <%= render partial: 'competition/tournament_seasons/bracket_set_head', locals: { of_winners_bracket: true } %>
  <% @matches[true][1][1].each do |match| %>
      <%= render partial: 'competition/tournament_seasons/bracket_set', locals: { 
        of_winners_bracket: true, match: match, first_matchday_matches_count: @matches[true][1][1].length
      } %>
  <% end %>
  
  <% if @is_double_elimination %>
      <%= render partial: 'competition/tournament_seasons/bracket_set_head', locals: { of_winners_bracket: false } %>
    <% @matches[false] ||= {} %> 
    <% @round_matches_index[false] ||= { 1 => 0} %>
    <% first_matchday_matches_count = (@matches[true][1][1].length / 2) %>
    <% first_matchday_matches_count.times do |first_loser_round_match_index| %>
      <% first_loser_round_match = @matches[false][1].try(:[], 2).try(:[], first_loser_round_match_index) %>
      <%= render partial: 'competition/tournament_seasons/bracket_set', locals: { 
        of_winners_bracket: false, match: first_loser_round_match, first_matchday_matches_count: first_matchday_matches_count
      } %>
    <% end %>
  <% end %>    
    </tbody>
  </table>
  
  <% if @can_update_season %>
  <p><%= submit_tag t('general.submit'), class: 'btn' %> <%= image_tag 'voluntary/spinner.gif', class: 'hide', id: 'bracket_matches_spinner' %></p>
  <% end %>
<% end %>

app/views/competition/tournament_seasons/_bracket_match_half.html.erb
<% rowspan = rowspan ? ' rowspan="' + rowspan.to_s + '"' : '' %>
<% rounds = of_winners_bracket ? @winner_rounds : @loser_rounds %>
<% with_second_leg = @with_second_leg && round != rounds ? true : false %>
<td<%= raw rowspan %> style="border:1px solid #AAAAAA;<%= side == :home ? ' border-bottom: 0px;' : '' %> border-right:0px; background:#F9F9F9; text-align:left; padding-left:1em; color:#000000;">
<% if matches.any? %>
    <%= link_to matches.first.send("#{side}_competitor").name, competition_competitor_path(matches.first.send("#{side}_competitor")) %>
<% else %>
    - 
<% end %>
  </td>
  <td<%= raw rowspan %> style="border:1px solid #AAAAAA;<%= side == :home ? ' border-bottom: 0px;' : '' %> <%= @with_second_leg ? 'border-right:0px;' : '' %> background:#F9F9F9; text-align:center;">
<% if matches.any? && matches.first.matchday == @season.current_matchday && matches.first.send("#{side}_goals").blank? && @can_update_season %>
    <input type="text" style="width:19px; text-align:center; position:relative; top:5px;" name="matches[<%= matches.first.id %>][<%= side %>_goals]" id="matches_<%= matches.first.id %>_<%= side %>_goals">   
<% else %>
    <%= matches.any? && matches.first.send("#{side}_goals") || '-' %>
<% end %>
  </td>
<% if with_second_leg %>
  <td<%= raw rowspan %> style="border:1px solid #AAAAAA;<%= side == :home ? ' border-bottom: 0px;' : '' %> border-right:0px; background:#F9F9F9; text-align:center;">
  <% second_leg_side = side == :home ? 'away' : 'home' %>
  <% goals = matches.any? ? matches.second.send("#{second_leg_side}_goals") : nil %>
  <% if matches.any? && matches.second.matchday == @season.current_matchday && goals.blank? && @can_update_season %>   
    <input type="text" style="width:19px; text-align:center; position:relative; top:5px;" name="matches[<%= matches.second.id %>][<%= second_leg_side %>_goals]" id="matches_<%= matches.second.id %>_<%= second_leg_side %>_goals">    
  <% else %>
    <%= goals || '-' %>
  <% end %>
  </td>
  <td<%= raw rowspan %> style="border:1px solid #AAAAAA;<%= side == :home ? ' border-bottom: 0px;' : '' %> background:#F9F9F9; text-align:center;">
  <% if matches.any? && matches.second.home_goals.present? %>
    <% if side == :home %>
    <%= matches.first.home_goals + matches.second.away_goals %>
    <% else %>
    <%= matches.first.away_goals + matches.second.home_goals %>
    <% end %>
  <% else %>
    -
  <% end %>
  </td>
<% end %>

app/views/competition/tournament_seasons/_bracket_set_head.html.erb
<% rounds = of_winners_bracket ? @winner_rounds : @loser_rounds - 1 %>
<tr>
  <td>&nbsp;</td>
<% rounds.times do |round| %>      
  <% with_second_leg = @with_second_leg && round + 1 != rounds ? true : false %>
  <td style="border:1px solid #AAAAAA; background:#F2F2F2; text-align:center;" colspan="<%= with_second_leg ? 4 : 2 %>">
    <%= round_title(of_winners_bracket, round + 1) %>
  </td>
  <% unless round + 1 == rounds %>    
  <td colspan="2"></td>
  <% end %>
<% end %>      
</tr>
<tr>
  <td>&nbsp;</td>     
<% rounds.times do |round| %>      
  <td style="width:125px;">&nbsp;</td>
  <td style="width:40px;">&nbsp;</td>
  <% if @with_second_leg && round + 1 != rounds %>
  <td style="width:40px;">&nbsp;</td>
  <td style="width:40px;">&nbsp;</td>
  <% end %>  
  <% unless round + 1 == rounds %>    
  <td style="width:15px;">&nbsp;</td>
  <td style="width:15px;">&nbsp;</td>
  <% end %>
<% end %>
</tr>   

app/views/competition/tournament_seasons/_join_or_leave.html.erb
<% if @season.participations.where(user_id: current_user.id).any? %>
  <%= link_to t('general.join_or_leave'), new_competition_season_participation_path(@season.id), class: 'remote_modal_link' %>
<% elsif @season.competitors_needed? %>
  <%= link_to t('general.join'), new_competition_season_participation_path(@season.id), class: 'remote_modal_link' %>
<% else %>
  <%= t('tournaments.general.no_more_competitors_needed') %>
<% end %>

app/views/competition/tournament_seasons/_third_place_playoff.html.erb
<% match = @matches[true].has_key?(@winner_rounds) ? @matches[true][@winner_rounds][@season.matchdays][1] : nil %>
<% case position %>
<% when 'first_round_bracket_row' %>
  <% multiplicator = @with_second_leg ? 6 : 4 %>
  <% if @winner_rounds == 2 && @round_matches_index[true][1] == @matches[true][1][1].length - 1 && side == :away %>
<td colspan="<%= (@winner_rounds - 2) * multiplicator + 1 %>">&nbsp;</td>
<td colspan="2" style="border:1px solid #AAAAAA; background:#F2F2F2; text-align:center; padding-left:1em;">
  <%= t('tournament_seasons.general.rounds.third_place') %>
</td>
  <% elsif @winner_rounds == 3 && @round_matches_index[true][1] == @matches[true][1][1].length - 1 && side == :away %>
    <% match = @matches[true].has_key?(@winner_rounds) ? @matches[true][@winner_rounds][@season.matchdays][1] : nil %>
<td colspan="<%= (@winner_rounds - 2) * multiplicator + 1 %>">&nbsp;</td>
<td style="border:1px solid #AAAAAA; border-right:0px; border-bottom:0px; background:#F9F9F9; padding-left:1em;">
  <%= match ? link_to(match.home_competitor.name, competition_competitor_path(match.home_competitor)) : '-' %>
</td>
<td style="border:1px solid #AAAAAA; border-bottom:0px; background:#F9F9F9; text-align:center;">
    <% if match.try(:matchday) == @season.current_matchday && match.home_goals.blank? && @can_update_season %>
  <input type="text" style="width:19px; position:relative; top:5px;" name="matches[<%= match.id %>][home_goals]" id="matches_<%= match.id %>_home_goals">   
    <% else %>    
  <%= match.try(:home_goals) || '-' %>
    <% end %>
</td>
  <% end %>
<% when 'bracket' %>
  <% multiplicator = @with_second_leg ? 4 : 2 %>
  
  <% if @winner_rounds == 2 %>
<tr>
  <td colspan="<%= (@winner_rounds - 1) * multiplicator + ((@winner_rounds - 2) * 2) + 3 %>">&nbsp;</td>
  <td colspan="2"></td>
</tr>  
<tr>
  <td colspan="<%= (@winner_rounds - 1) * multiplicator + ((@winner_rounds - 2) * 2) + 3 %>">&nbsp;</td>
  <td style="border:1px solid #AAAAAA; border-right:0px; border-bottom: 0px; background:#F9F9F9; padding-left:1em;">
    <%= match ? link_to(match.home_competitor.name, competition_competitor_path(match.home_competitor)) : '-' %>
  </td>
  <td style="border:1px solid #AAAAAA; border-bottom: 0px; background:#F9F9F9; text-align:center;">
  <% if match.try(:matchday) == @season.current_matchday && match.home_goals.blank? && @can_update_season %>
    <input type="text" style="width:19px; position:relative; top:5px;" name="matches[<%= match.id %>][home_goals]" id="matches_<%= match.id %>_home_goals">   
  <% else %>    
    <%= match.try(:home_goals) || '-' %>
  <% end %>
  </td>
</tr>
  <% end %>
<tr>
  <td colspan="<%= (@winner_rounds - 1) * multiplicator + ((@winner_rounds - 2) * 2) + 3 %>">&nbsp;</td>
  <td style="border:1px solid #AAAAAA; border-right:0px; background:#F9F9F9; padding-left:1em;">
    <%= match ? link_to(match.away_competitor.name, competition_competitor_path(match.away_competitor)) : '-' %>
  </td>
  <td style="border:1px solid #AAAAAA;  background:#F9F9F9; text-align:center;">
  <% if match.try(:matchday) == @season.current_matchday && match.away_goals.blank? && @can_update_season %>
    <input type="text" style="width:19px; position:relative; top:5px;" name="matches[<%= match.id %>][away_goals]" id="matches_<%= match.id %>_away_goals">   
  <% else %>    
    <%= match.try(:away_goals) || '-' %>
  <% end %>
  </td>
</tr>
<% when 'after_first_round_bracket_match_top' %>
  <% multiplicator = @with_second_leg ? 6 : 4 %>
<td colspan="<%= 1 * multiplicator + 1 %>">&nbsp;</td>
<td style="border:1px solid #AAAAAA; border-right:0px; border-bottom:0px; background:#F9F9F9; padding-left:1em;">
  <%= match ? link_to(match.home_competitor.name, competition_competitor_path(match.home_competitor)) : '-' %>
</td>
<td style="border:1px solid #AAAAAA; border-bottom:0px; background:#F9F9F9; text-align:center;">
  <% if match.try(:matchday) == @season.current_matchday && match.home_goals.blank? && @can_update_season %>
  <input type="text" style="width:19px; position:relative; top:5px;" name="matches[<%= match.id %>][home_goals]" id="matches_<%= match.id %>_home_goals">   
  <% else %>    
  <%= match.try(:home_goals) || '-' %>
  <% end %>
</td>
<% when 'after_first_round_bracket_match_between' %>
  <% multiplicator = @with_second_leg ? 6 : 4 %>
<td colspan="<%= 1 * multiplicator + 1 %>" rowspan="2">&nbsp;</td>
<td  rowspan="2" style="border:1px solid #AAAAAA; border-right:0px; background:#F9F9F9; padding-left:1em;">
  <%= match ? link_to(match.away_competitor.name, competition_competitor_path(match.away_competitor)) : '-' %>
</td>
<td rowspan="2" style="border:1px solid #AAAAAA; background:#F9F9F9; text-align:center;">
  <% if match.try(:matchday) == @season.current_matchday && match.away_goals.blank? && @can_update_season %>
  <input type="text" style="width:19px; position:relative; top:5px;" name="matches[<%= match.id %>][away_goals]" id="matches_<%= match.id %>_away_goals">   
  <% else %>    
  <%= match.try(:away_goals) || '-' %>
  <% end %>
</td>
<% when 'after_first_round_bracket_match_bottom_only_round_title' %>
<td rowspan="2">&nbsp;</td>
<td style="text-align:center; background-color:#F2F2F2; border:1px solid #aaa;" colspan="2" rowspan="2"><%= t('tournament_seasons.general.rounds.third_place') %></td>
<% end %>

app/views/competition/tournament_seasons/bracket.html.erb
<% if @season.active? %>
<div id="tournament_bracket">
  <%= render partial: 'competition/tournament_seasons/bracket' %>
</div>
  <% content_for :javascript_includes do %>
    <%= javascript_include_tag 'voluntary_competition/seasons/bracket' %>
  <% end %>
<% else %>
  <p><%= I18n.t('tournament_seasons.bracket.unavailable')%></p>
<% end %>